[package]
name = "gpu-share-vm-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
virt = "0.3.0"  
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"  
async-trait = "0.1"
config = "0.14"
axum = "0.6"
tower = "0.4"
tower-http = { version = "0.4", features = ["trace"] }