apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-share-config
  namespace: gpu-share
data:
  default.toml: |
    [server]
    host = "0.0.0.0"
    port = 3000
    api_prefix = "/api/v1"

    [libvirt]
    connection_uri = "qemu:///system"
    max_vms = 10
    default_memory_mb = 4096
    default_vcpus = 2

    [monitoring]
    metrics_interval_seconds = 5
    retention_hours = 24
    enable_gpu_metrics = true

    [storage]
    vm_image_path = "/var/lib/gpu-share/images"
    max_storage_gb = 100