apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-images-pvc
  namespace: gpu-share
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard